# Generated by Django 5.2.9 on 2025-12-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminnotifications',
            fields=[
                ('notificationid', models.AutoField(db_column='NotificationID', primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Message', max_length=255, null=True)),
                ('createdat', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('isread', models.BooleanField(blank=True, db_column='IsRead', null=True)),
            ],
            options={
                'db_table': 'AdminNotifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookid', models.AutoField(db_column='BookID', primary_key=True, serialize=False)),
                ('bookname', models.CharField(db_collation='Turkish_CI_AS', db_column='BookName', max_length=100)),
                ('categoryid', models.IntegerField(db_column='CategoryID')),
                ('author', models.CharField(db_collation='Turkish_CI_AS', db_column='Author', max_length=100)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField(db_column='Stock')),
                ('imageurl', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='ImageUrl', max_length=300, null=True)),
                ('averagerating', models.DecimalField(blank=True, db_column='AverageRating', decimal_places=2, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'Books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cartitems',
            fields=[
                ('cartitemid', models.AutoField(db_column='CartItemID', primary_key=True, serialize=False)),
                ('bookid', models.IntegerField(db_column='BookID')),
                ('quantity', models.IntegerField(db_column='Quantity')),
            ],
            options={
                'db_table': 'CartItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('cartid', models.AutoField(db_column='CartID', primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(db_column='CreatedAt')),
            ],
            options={
                'db_table': 'Carts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryid', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(db_collation='Turkish_CI_AS', db_column='CategoryName', max_length=100)),
            ],
            options={
                'db_table': 'Categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('favoriteid', models.AutoField(db_column='FavoriteID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='UserID')),
                ('bookid', models.IntegerField(db_column='BookID')),
            ],
            options={
                'db_table': 'Favorites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderitems',
            fields=[
                ('orderitemid', models.AutoField(db_column='OrderItemID', primary_key=True, serialize=False)),
                ('orderid', models.IntegerField(db_column='OrderID')),
                ('bookid', models.IntegerField(db_column='BookID')),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('productprice', models.DecimalField(db_column='ProductPrice', decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'OrderItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(db_column='OrderID', primary_key=True, serialize=False)),
                ('customerid', models.IntegerField(db_column='CustomerID')),
                ('statuss', models.CharField(db_collation='Turkish_CI_AS', db_column='Statuss', max_length=30)),
                ('orderdate', models.DateTimeField(db_column='OrderDate')),
                ('totalamount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=10)),
                ('shippingaddress', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='ShippingAddress', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderstatushistory',
            fields=[
                ('historyid', models.AutoField(db_column='HistoryID', primary_key=True, serialize=False)),
                ('orderid', models.IntegerField(blank=True, db_column='OrderID', null=True)),
                ('oldstatus', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='OldStatus', max_length=50, null=True)),
                ('newstatus', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='NewStatus', max_length=50, null=True)),
                ('changedate', models.DateTimeField(blank=True, db_column='ChangeDate', null=True)),
            ],
            options={
                'db_table': 'OrderStatusHistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('rewiewid', models.AutoField(db_column='RewiewID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='UserID')),
                ('bookid', models.IntegerField(db_column='BookID')),
                ('star', models.IntegerField()),
                ('comment', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Comment', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_collation='Turkish_CI_AS', db_column='FullName', max_length=100)),
                ('email', models.CharField(db_collation='Turkish_CI_AS', db_column='Email', max_length=150, unique=True)),
                ('passwordhash', models.CharField(db_collation='Turkish_CI_AS', db_column='PasswordHash', max_length=200)),
                ('usertype', models.CharField(blank=True, db_collation='Turkish_CI_AS', db_column='Usertype', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
