# Generated by Django 5.2.9 on 2025-12-21 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'managed': True},
        ),
    ]
