"""
Django settings for KitapKurdu project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# This is how we created the roads within the project.
BASE_DIR = Path(__file__).resolve().parent.parent

# Django's secret key used for encryption.
SECRET_KEY = "django-insecure-*ab23qnp2u-q9+wnxtn@=t$6qeyrommipdb)8mp8ztzxwj^@)k"

# Active to see errors
DEBUG = True
ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    "store",  # The main module of the Bookworm project
    "django.contrib.admin",  # Admin panel
    "django.contrib.auth",  # User and authorization system
    "django.contrib.contenttypes",
    "django.contrib.sessions",  # Session management (for Login/Logout operations)
    "django.contrib.messages",  # Used to display a message to the user (e.g., "Successfully logged in")
    "django.contrib.staticfiles",  # Managing CSS, JS, and image files
]

# The section where requests and responses are processed
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",  # Session management
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",  # Kullanıcı giriş kontrolü
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# The main file where URL redirects are made (urls.py)
ROOT_URLCONF = "KitapKurdu.urls"

# HTML SETTINGS
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "design"],  # Location of HTML files
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.debug",
                "store.context_processors.get_cart_count",  # The processor we wrote to display the number of baskets on each page.
            ],
        },
    },
]

WSGI_APPLICATION = "KitapKurdu.wsgi.application"


# === DATABASE SETTINGS (MSSQL) ===

# The project is configured to use Microsoft SQL Server (MSSQL).
DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": "KitapKurduDB",  # SQL Server'daki veritabanı adın
        "USER": "",
        "PASSWORD": "",
        "HOST": "localhost",
        "PORT": "",
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server",  # The necessary driver for Python to communicate with SQL Server.
        },
    }
}


# === PASSWORD VERIFICATION ===
# Rules that prevent users from using very simple passwords (e.g., 12345).
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
LANGUAGE_CODE = "tr"

TIME_ZONE = "Europe/Istanbul"

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# default key setting
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
